import uuid
from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class User(Base):
    """The users table."""

    __tablename__ = "users"

    # UUID rather than an auto-incrementing integer.
    # Three reasons, all worth stating in the viva:
    #   1. IDs can be generated by any service without coordination,
    #      which matters in a distributed system.
    #   2. No collisions if data from multiple regions is merged.
    #   3. Not guessable, so an attacker cannot enumerate users
    #      by walking /users/1, /users/2, /users/3.
    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )

    email: Mapped[str] = mapped_column(
        String(255), unique=True, index=True, nullable=False
    )
    full_name: Mapped[str] = mapped_column(String(255), nullable=False)

    # Only ever the hash. The plaintext password is never stored,
    # never logged, and never returned by any endpoint.
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)

    # Role drives RBAC: customer, warehouse, admin.
    role: Mapped[str] = mapped_column(String(32), nullable=False, default="customer")

    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )