# Export the OpenAPI specification from every running service.
#
# The specs are generated by FastAPI from the route definitions and type
# annotations, so they cannot drift out of step with the implementation.
# Committing them gives reviewers the API contract without needing the
# stack running, and allows the contract to be diffed between versions.
#
# Usage:  .\scripts\export-specs.ps1

$ErrorActionPreference = "Continue"
$out = "api-specs"
New-Item -ItemType Directory -Force -Path $out | Out-Null

$services = [ordered]@{
    "user-service"         = 8001
    "catalogue-service"    = 8002
    "order-service"        = 8003
    "inventory-service"    = 8004
    "payment-service"      = 8005
    "notification-service" = 8006
}

$summary = @()

foreach ($name in $services.Keys) {
    $port = $services[$name]
    $url  = "http://localhost:$port/openapi.json"

    try {
        $raw  = Invoke-RestMethod -Uri $url -TimeoutSec 10
        $json = $raw | ConvertTo-Json -Depth 100
        $path = Join-Path $out "$name.openapi.json"
        $json | Out-File -FilePath $path -Encoding utf8

        $endpoints = ($raw.paths.PSObject.Properties | Measure-Object).Count

        Write-Host ("  {0,-22} OAS {1}  v{2}  {3} paths" -f `
                    $name, $raw.openapi, $raw.info.version, $endpoints) -ForegroundColor Green

        $summary += [PSCustomObject]@{
            Service = $name
            Port    = $port
            OpenAPI = $raw.openapi
            Version = $raw.info.version
            Paths   = $endpoints
        }
    }
    catch {
        Write-Host ("  {0,-22} FAILED - is the service running?" -f $name) -ForegroundColor Red
    }
}

Write-Host ""
$summary | Format-Table -AutoSize
Write-Host "Specifications written to $out\" -ForegroundColor Cyan
